name: Static Analysis

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # Prepare Android SDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: ${{ matrix.api-level }}
        build-tools: '30.0.3'

    # Build the project using Gradle
    - name: Build with Gradle
      run: ./gradlew assemble${{ matrix.target }}

    # Run tests
    - name: Run unit tests
      run: ./gradlew test

    - name: Run Ktlint
      run: ./gradlew ktlintStagingDebugCheck

    - name: Run Unit Tests
      run: ./gradlew testStagingDebugUnitTest

    - name: Run Linters and Test
      run: ./gradlew check
    # If you want to run instrumentation tests (UI tests), use:
    # - name: Run instrumentation tests
    #   run: ./gradlew connectedAndroidTest
  detekt:
    name: Detekt
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Runs a single command using the runners shell
      - name: detekt
        run: ./gradlew detekt

  spotless:
    name: Spotless
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Runs a single command using the runners shell
      - name: spotless
        run: ./gradlew spotlessCheck